# Generated by Django 4.0.4 on 2022-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
