# Generated by Django 4.0.4 on 2022-05-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Sold',
        ),
    ]
