# Generated by Django 4.0.4 on 2022-06-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_product_image_alter_product_title'),
        ('app', '0003_product_rating'),
    ]

    operations = [
    ]
