# Generated by Django 4.0.4 on 2022-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
