# Generated by Django 4.0.4 on 2022-06-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orderplaced_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='website',
        ),
    ]
