# Generated by Django 4.0.4 on 2022-06-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='website',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
