# Generated by Django 4.0.4 on 2022-06-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sentiment',
        ),
    ]
